# Generated by Django 3.1.11 on 2021-05-17 00:41

import autoslug.fields
from django.db import migrations, models
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('full_name', models.CharField(max_length=255, verbose_name='Full Name')),
                ('slug', autoslug.fields.AutoSlugField(always_update=True, editable=False, populate_from='full_name', unique=True, verbose_name='Actor URL')),
                ('short_name', models.CharField(max_length=255, verbose_name='First name, short name, or use-name')),
                ('bio', models.TextField(verbose_name='Bio')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
