# Generated by Django 3.1.11 on 2021-05-17 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actors', '0002_auto_20210517_0212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='bio',
            field=models.TextField(blank=True, verbose_name='Bio'),
        ),
        migrations.AlterField(
            model_name='actor',
            name='short_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='First name, short name, or use-name'),
        ),
    ]
