# Generated by Django 3.1.11 on 2021-05-17 05:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0001_initial'),
        ('actors', '0004_actor_creator'),
    ]

    operations = [
        migrations.AddField(
            model_name='actor',
            name='characters',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='characters.character'),
        ),
    ]
