# Generated by Django 3.1.11 on 2021-05-17 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('actors', '0005_actor_characters'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actor',
            name='characters',
        ),
    ]
