# Generated by Django 3.1.11 on 2021-05-17 06:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('actors', '0006_remove_actor_characters'),
        ('characters', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='actors',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='actors.actor'),
        ),
    ]
